CREATE TABLE IF NOT EXISTS site_actions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  action_type VARCHAR(50) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_date (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
